dist: trusty

os: linux

services:
  - docker
  - postgresql

language: java

before_install:
  - docker run -p 50000:50000 -v "`pwd`/test_vm/scripts/db2:/scripts" -e DB2INST1_PASSWORD=db2inst1-pwd -e LICENSE=accept --name dbfitdb2 --privileged=true cwds/db2 &
  - docker run -p 1521:1521 -p 49160:22 -v "`pwd`/test_vm/scripts/oracle/sql:/docker-entrypoint-initdb.d:ro" wnameless/oracle-xe-11g-r2 &
  - "./gradlew -version"

install: "./gradlew assemble"

before_script:
  - mysql -u root -v < dbfit-java/mysql/src/integration-test/resources/create-db-mysql.sql
  - ./test_vm/scripts/postgresql/install_postgresql.sh
  - docker ps -a
  - docker images ls
  - docker logs dbfitdb2
  - for i in {1..60}; do echo "$i waiting for Oracle server startup"; echo | nc -w1 localhost 49160 >/dev/null 2>&1 ;echo $? | grep 0 && echo "[Oracle UP]" && break || sleep 6; done
  - for i in {1..60}; do echo "$i waiting for DB2 server startup"; docker exec dbfitdb2 /scripts/detect_dbstart.sh 2 && echo "[DB2 UP]" && break || sleep 6; done
  - docker exec dbfitdb2 /scripts/create_db_schema.sh

script:
  - ./gradlew --continue clean travisbuild
  - ./gradlew bundle

jdk:
  - openjdk7
  - openjdk8

addons:
  artifacts:
    paths:
      - zips/
    target_paths: artifacts/$TRAVIS_REPO_SLUG/$TRAVIS_BUILD_NUMBER/$TRAVIS_JOB_NUMBER
    region: us-east-1

env:
  jobs:
    secure: gOEl7TFI3RH0cMkSNOXeSwC0ZCF60/JSftuTK0Y7UZtSS4yEYkn4o2RX/PO3I+3kQdpkbx9pe+lnd1+C1to1QJqd4AhOGwoy/7KvTE+qCP0bdOLSWUbWJ92SmI/ZPijnODfcFWWkCDIhQBK0SEinVokjD5PPobDwGMosDMS2Qzo=
